### PR TITLE
Sys functions improvements

### PR DESCRIPTION
**Pull request by ximex**
i hope i found all wrong types

### CODE REVIEW

**Comment by MyIgel** [comment]
I am somehow pretty sure that its a bad idea to use `declare(strict_types=1);` in any legacy code from the `includes` dir.
Same goes for introducing types there -> just letting the old code sit there and don't touching it is normally a wise choice (and replacing it with newly written implementations).

**Comment by ximex** [comment]
I don't know anything against it. also if we know that the includes code would get completely replaced in the future. And the next usage is far in the future if we overlooked a case that would cause a crash. so much testing time

**Comment by MyIgel** [comment]
The point here is that the old code relies on interesting type interpretations and changes which strict types could eventually break.
 I highly personally prefer to keep the changes inside that dir to a bare minimum and that includes not adding that many types and definitely not adding strict typing  there.

**Comment by weeman1337** [comment]
My opinion on this: Don't mess too much around with `includes`.

**Comment by msquare** [comment]
Sorry, we agreed to not mess with the legacy code too much.

**Pull request closed without merging**
