### PR TITLE
Improve navbar

### PR DESCRIPTION
**Pull request by ximex**
- Improvements that the navbar has the same height on smaller windows
- fix language switching
- move some code from includes to twig templates
- move popover js code to js file
- extract language selection into own menu entry
- other minor improvements (see commits)

### CODE REVIEW

**Comment by ximex** [comment]
should we maybe use list-groups instead of alerts for the notification popover?
https://getbootstrap.com/docs/5.2/components/list-group/#contextual-classes

**Comment by weeman1337** [comment]
@ximex can you run `yarn run lint:fix` please? And it would be helpful if you can check „Allow edits from maintainers“ for your PRs.

**Review by weeman1337 — CHANGES_REQUESTED** [review]
@ximex can you run `yarn run lint:fix` please? And it would be helpful if you can check „Allow edits from maintainers“ for your PRs.

**Comment by ximex** [comment]
fixed. couldn't find this option. where is this?

**Comment by MyIgel** [comment]
@ximex 
image

**Review by weeman1337 — APPROVED** [review]

**Pull request merged**
