### PR TITLE
rename `docker-compose` to `docker compose`

### PR DESCRIPTION
**Pull request by ximex**
`docker compose` is the newer way

### CODE REVIEW

**Comment by weeman1337** [comment]
Reading [this](https://github.com/docker/compose/tree/v2#about-update-and-backward-compatibility) we should really do some testing before merging this. Eventually also provide a link tot he instructions.

**Comment by ximex** [comment]
i worked all the time with `docker compose` for now and had no issue so far

**Comment by MyIgel** [comment]
I don't think that it's that much of a problem as we are not using many "advanced" features (and i had no problems here too) so moving on should be fine but this branch needs a rebase (or rebuild as its easier ;)) which only @ximex can do as its a PR from an org.

**Comment by ximex** [comment]
done

**Pull request merged**
