### PR TITLE
minor typo fixed (sheduler to scheduler)

### PR DESCRIPTION
**Pull request by anykraus**

### CODE REVIEW

**Comment by msquare** [comment]
Thank you. Would you mind to update the language files too? They should contain the typo as well, since the sentence is used as "key".

**Comment by anykraus** [comment]
Should I trigger a new pull request? (Or should I do the refresh of the language files based on the current HEAD?)

**Comment by msquare** [comment]
Since the language files changed a lot since creating your fix, please make a new pull request based on the current HEAD. Thanks!

**Comment by anykraus** [comment]
Prepared commit 568f71928b4492d35b051e279316d2583fb718fd that updates current HEAD lang files. (May remove strings that are planned for future use.)

**Pull request merged**
