### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by ximex**
uppercase the keywords in dockerfile
update `node:14-alpine` to `node:18-alpine` image

### CODE REVIEW

**Comment by MyIgel** [comment]
I would personally wait 'till node 20.x which will get updates until 2026-04-30 (and will be released ~2023-04-18) as we have no need to update it but :man_shrugging:

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Same opinion as Igel. We do only use this for builds and not in production. So there is no need to rush for newer versions here, unless it would block us from using newer/other tooling. :heavy_plus_sign: for waiting for the next LTS

**Comment by MyIgel** [comment]
The next LTS is planned for `2023-04-18`

**Comment by weeman1337** [comment]
> The next LTS is planned for `2023-04-18`

That was yesterday @ximex , go ! :laughing:

**Comment by ximex** [comment]
docker image not available yet for node v20: https://hub.docker.com/_/node

**Comment by ximex** [comment]
here it is ;-)

**Comment by ximex** [comment]
now the images is available

**Pull request merged**
