### PR TITLE
Further API fixes & improvements

### PR DESCRIPTION
**Pull request by MyIgel**
* Fixed event time..
* Documented `x-api-key` header for authentication

### CODE REVIEW

**Comment by xuwhite** [comment]
put put put

**Comment by xuwhite** [comment]
pls add doku

**Review by xuwhite — CHANGES_REQUESTED** [review]
Barer auth doesnt work for me

**Comment by MyIgel** [comment]
The bearer auth now also trims any additional spaces added and thus should resolve your issue (also added `access-control-allow-origin` to not authorized responses so that requesting applications can properly react instead of triggering browser protection mechanics)

**Review by xuwhite — CHANGES_REQUESTED** [review]
pls fix that on a new angelsystem you have to reset the api key first before getting an api key

**Comment by MyIgel** [comment]
That is only relevant for the admin user and thus another issue that should be solved on user creation -> @xuwhite  can you open a new issue for that?

**Review by weeman1337 — APPROVED** [review]
Looks good

**Pull request merged**
