### PR TITLE
WIP: Add div and css to expand shift panel on hover fixes #526

### LINKED ISSUE #526: Not all angels shown in shift overview
In the user-shift overview, when the event is too short, only the first angeltypes are shown and the other are getting cut off.
grafik

### PR DESCRIPTION
**Pull request by wonko21**
Implementation idea stolen from http://jsfiddle.net/6K7t4/24/

### CODE REVIEW

**Comment by msquare** [comment]
Is it possible to do this on click and not on mouseover? Mouseover happens accidently and you may not be able to acces the shift below.

**Comment by wonko21** [comment]
Very possible but might involve some js.Do you have a db dump somewhere that I can use to go through "real" use cases? 
@MyIgel  already wihed for the cards not beeing cut of on overflow.

**Comment by msquare** [comment]
Create 2h shifts that need 3 different angel types for your testcase. JS for this would be ok if without js the shift panel is not extended.

**Comment by wonko21** [comment]
closing in favor of new pr

**Pull request closed without merging**
