### PR TITLE
replace sticky-headers javascript impl with css

### PR DESCRIPTION
**Pull request by ximex**
use css instead of js for sticky headers in shift table. prevents flickering on scrolling.
add background color for first column heading to prevent overlapping text

### CODE REVIEW

**Review by MyIgel — CHANGES_REQUESTED** [review]
This only makes the top bar sticky but ignores the times at the side which need to be sticky when scrolling sidewise (happens when too much shifts (~6) are in parallel)

**Comment by ximex** [comment]
fixed

**Comment by MyIgel** [comment]
Hmm at some point the bar sits below the menu and sometimes it still scrolls outside the viewport:

Screenshot_20230122_204305

**Comment by ximex** [comment]
rebased
@MyIgel pls test again. with the merged PR of the navbar this problem should be gone

**Pull request merged**
