### PR TITLE
Shift table view

### PR DESCRIPTION
**Pull request by PowerPan**
Add Table View For Shifts
Bildschirmfoto 2022-07-16 um 00 30 56

### CODE REVIEW

**Comment by PowerPan** [comment]
@MyIgel @weeman1337 what i have to do for merging?

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Hey @PowerPan :wave: Can you fix the issues mentioned by previous reviewers and solve the conflicts in your branch? If we don't hear from you for another two weeks, we may unfortunately close this pull request.

**Comment by weeman1337** [comment]
If you want to continue working on this after two weeks, just leave comment here so that we can reopen the pull request.

**Comment by MyIgel** [comment]
On the other side as noted above:
:exclamation:  This is a feature that needs to be maintained and heavily relies on legacy code.

**Pull request closed without merging**
