### PR TITLE
Make user view columns dynamic by config

### PR DESCRIPTION
**Pull request by PowerPan**

### CODE REVIEW

**Comment by xuwhite** [comment]
Please have a look at the [contributing guidelines](https://github.com/engelsystem/engelsystem/blob/main/CONTRIBUTING.md), especially the parts about meaningful commit messages, squashing and code style. Also don't drag your old commits through pull requests.

**Comment by PowerPan** [comment]
@xuwhite ok i will fix this
@MyIgel i use the engelsystem for a big sportevent and for example we don't work with the "User " names in the frontend. We allways use the Full name. So in our Admin view we have at the moment only visible the columns
* FristName
* LastName
* Arrvied
* LastLogin

I had make some more pullrequests where i optimize the system and make it more configurable for non chaos events ;)

**Comment by MyIgel** [comment]
Hi @PowerPan , did you had time to fix the issues and rebase the branch so that it can be merged?

**Review by MyIgel — CHANGES_REQUESTED** [review]
Hi @PowerPan , did you had time to fix the issues and rebase the branch so that it can be merged?

**Comment by weeman1337** [comment]
Hey @PowerPan . Can you fix the issues mentioned by previous reviewers and solve the conflicts in your branch? If we don't hear from you for another two weeks, we may unfortunately close this pull request.

**Comment by weeman1337** [comment]
If you want to continue working on this after two weeks, just leave comment here so that we can reopen the pull request.

**Comment by MyIgel** [comment]
With a simple cherry pick and styling fixes this PR is ready for merging.

**Pull request merged**
