### PR TITLE
Hotfix php7 syntax error

### PR DESCRIPTION
**Pull request by flyingapfopenguin**
die is a reserved keyword and php7 throws a syntax error

### CODE REVIEW

**Comment by msquare** [comment]
Nice. Please consider another funny word in english, something like `terminate_application_immediately`.
;-)

**Comment by flyingapfopenguin** [comment]
I thought this might come up.

**Comment by msquare** [comment]
Great, thank you!

**Comment by MyIgel** [comment]
The tests in `tests/Unit/Exceptions/HandlerTest.php#L49` need to be fixed

**Pull request merged**
