### PR TITLE
Issue 773: Message "Shift ends"

### PR DESCRIPTION
**Pull request by herzmut**
solves issue #773

### CODE REVIEW

**Comment by MyIgel** [comment]
Does it? -> Needs further testing as i'm unshure :D

**Comment by herzmut** [comment]
Should I write a unit test to cover that case?

**Comment by MyIgel** [comment]
What I mean is that the part that shows the time in the frontend gets updated by js which itself has to get updated, not the backend code.
The backend itself normally shows either "No shifts" or directly the next shift so i wonder how to even get to this line?

**Comment by MyIgel** [comment]
Even more interestingly, my ci run does not require the default values patch? hmm

**Comment by herzmut** [comment]
That's strange. However, if the JavaScript is not in another repository and composed with this one on a build, it does not seem render these time values on its own but gets it as a template fragment from the backend. Is there any state of the application where you could view a shift which ended, like a detail view of done shifts? The only other option would be to leave the tab open over the end of the shift, so the one-time fetched moment.js template keeps on updating the placeholder without changing the sentence. True, this PR does not solve that yet.

**Comment by msquare** [comment]
The change does not solve the problem.

**Pull request closed without merging**
