### PR TITLE
Test installation show more dependencies

### PR DESCRIPTION
**Pull request by shithead**
yarn need npm

test installation on FreeBSD

### CODE REVIEW

**Comment by astro** [comment]
Doesn't yarn replace npm?

**Comment by shithead** [comment]
@astro I run yarn in directory engelsystem, it called 'npm install ...'.

**Comment by shithead** [comment]
oh i have correct me it called:

`    "build": "npm run -s build:clean && NODE_ENV=production run-p build:assets build:webpack",`

**Comment by marudor** [comment]
Technically npm is a requirement. Although we use yarn (alternative to npm, they use the same infrastructure though - just different handling on your computer) it is recommended to use npm in package.json.
As node always provices npm we shouldn't put it in the requirements.

**Comment by shithead** [comment]
@marudor 

> As node always provides npm we shouldn't put it in the requirements.
That's wrong! On FreeBSD it not provide per default.

See Source build:
* [npm versions](https://www.freshports.org/search.php?query=npm&search=go&num=10&stype=name&method=match&deleted=excludedeleted&start=1&casesensitivity=caseinsensitive)
* node versions
  * [node10](https://www.freshports.org/www/node10/)
  * [node6](https://www.freshports.org/www/node6/)
  * [node8](https://www.freshports.org/www/node8/)

fresh pkg install:
```
[vagrant@bazinga ~]$  pkg install node8
> New packages to be INSTALLED:
> 	node8: 8.15.1
> 	icu: 63.1_1,1
> 	c-ares: 1.14.0_2
> 	libuv: 1.27.0

```
after installation:
```
[vagrant@bazinga ~]$ npm
-bash: npm: command not found
```
```
[vagrant@bazinga ~]$ sudo pkg install npm-node8

> New packages to be INSTALLED:
> 	npm-node8: 6.9.0
> 	gmake: 4.2.1_3
```

```
[vagrant@bazinga ~]$ npm

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/vagrant/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.9.0 /usr/local/lib/node_modules/npm
```

**Comment by marudor** [comment]
So the FreeBSD Maintainer decided to split it. That's exactly what node doesn't want.
Guess we can add it - but mark it as "This should be included in your node install"
It's exotic to not bundle it.

**Comment by MyIgel** [comment]
Or maybe write it as `Node >= 8 (should come with npm)` or something

**Comment by shithead** [comment]
@marudor 
The FreeBSD Port Maintainer do you mean is Bryan Hughes. He is [member of Technical Steering Committee Emeriti](https://github.com/nodejs/node).

FYI:

Fedora29: `dnf install node npm`
Arch Linux: `pacman -S nodejs npm`
Windows: You has the option to install node and npm separate. (Split installation is want)

I create a commit with  "This should be included in your node install" next time.

**Pull request merged**
