### PR TITLE
Allow password-less registration

### LINKED ISSUE #844: SSO-Only registration / login
Please allow registration and login to only be allowed via SSO / oauth2.

This would mean:
- add a configuration variable defaulting to allow password-less registration
  - possibly: only allow password-less registration in the oauth2 flow, but require a password when registering without a linked SSO account
- add a configuration variable to disallow registration without using oauth2.
- add a configuration variable to disallow password-based login, hiding the username/password fields.

### PR DESCRIPTION
**Pull request by fabianfreyer**
Introduce a configuration option that, when unset, causes registration to not require setting a password. Users registered without a password will not be able to login unless through SSO.

A possible follow-up would be to only enforce this in the oauth2 registration flow, but still require a password to be set when registering without SSO.

closes #844

### CODE REVIEW

**Comment by MyIgel** [comment]
That will just break the "normal" registration flow which is bad and does not allow to set a new password in the user settings. The later i'v fixed, for the first i'm working on a possible solution.

**Comment by MyIgel** [comment]
But somehow i am not able to push to your branch even if it look like you have enabled it for this PR? If not please tick the checkmark for "allow maintainers to push to this repo"

Patch:
```diff
From 25ee76d3dfdbcefc97d9efbf9883487c1c797c11 Mon Sep 17 00:00:00 2001
From: Igor Scheller <igor.scheller@igorshp.de>
Date: Thu, 9 Dec 2021 23:39:46 +0100
Subject: [PATCH] Allow empty password in settings

---
 config/config.default.php                     |  4 +--
 resources/lang/en_US/default.po               |  1 +
 resources/views/pages/settings/password.twig  | 15 ++++++----
 src/Controllers/SettingsController.php        |  8 ++---
 .../Controllers/SettingsControllerTest.php    | 30 +++++++++++++++++++
 5 files changed, 46 insertions(+), 12 deletions(-)

diff --git a/config/config.default.php b/config/config.default.php
index 2a9f80ec..47a7374a 100644
--- a/config/config.default.php
+++ b/config/config.default.php
@@ -228,8 +228,8 @@ return [
     // The minimum length for passwords
     'min_password_length'     => env('PASSWORD_MINIMUM_LENGTH', 8),
 
-    // Whether the Password field should be enabled.
-    // If this is disabled, it means that no password can be set and the user will
+    // Whether the Password field should be enabled on registration.
+    // If this is disabled, it means that no password can be set on registration so the user will
     // not be able to log in unless linked to an oauth provider.
     'enable_password'         => (bool)env('ENABLE_PASSWORD', true),
 
diff --git a/resources/lang/en_US/default.po b/resources/lang/en_US/default.po
index 81f4a4e7..b38cedc4 100644
--- a/resources/lang/en_US/default.po
+++ b/resources/lang/en_US/default.po
@@ -21,6 +21,7 @@ msgstr ""
 
 #~ msgid "auth.no-password"
 #~ msgstr "Please enter a password."
+
 msgid "auth.password.error"
 msgstr "Your password is incorrect. Please try it again."
 
diff --git a/resources/views/pages/settings/password.twig b/resources/views/pages/settings/password.twig
index 7d4ebcab..1902135d 100644
--- a/resources/views/pages/settings/password.twig
+++ b/resources/views/pages/settings/password.twig
@@ -11,12 +11,15 @@
             <div class="row">
                 <div class="col-md-12">
                     {{ m.info(__('settings.password.info')) }}
-                    {{ f.input(
-                        'password',
-                        __('settings.password.password'),
-                        'password',
-                        {'required': true}
-                    ) }}
+
+                    {% if user.password %}
+                        {{ f.input(
+                            'password',
+                            __('settings.password.password'),
+                            'password',
+                            {'required': true}
+                        ) }}
+                    {% endif %}
                     {{ f.input(
                         'new_password',
                         __('settings.password.new_password'),
diff --git a/src/Controllers/SettingsController.php b/src/Controllers/SettingsController.php
index 03882f00..4db1aa54 100644
--- a/src/Controllers/SettingsController.php
+++ b/src/Controllers/SettingsController.php
@@ -77,12 +77,12 @@ class SettingsController extends BaseController
 
         $minLength = config('min_password_length');
         $data = $this->validate($request, [
-            'password' => 'required',
-            'new_password' => 'required|min:' . $minLength,
-            'new_password2' => 'required'
+            'password'      => 'required' . (empty($user->password) ? '|optional' : ''),
+            'new_password'  => 'required|min:' . $minLength,
+            'new_password2' => 'required',
         ]);
 
-        if (!$this->auth->verifyPassword($user, $data['password'])) {
+        if (!empty($user->password) && !$this->auth->verifyPassword($user, $data['password'])) {
             $this->addNotification('auth.password.error', 'errors');
         } elseif ($data['new_password'] != $data['new_password2']) {
             $this->addNotification('validation.password.confirmed', 'errors');
diff --git a/tests/Unit/Controllers/SettingsControllerTest.php b/tests/Unit/Controllers/SettingsControllerTest.php
index 90b2dc10..f1a33eb8 100644
--- a/tests/Unit/Controllers/SettingsControllerTest.php
+++ b/tests/Unit/Controllers/SettingsControllerTest.php
@@ -99,6 +99,36 @@ class SettingsControllerTest extends TestCase
         $this->assertEquals('settings.password.success', $messages[0]);
     }
 
+    /**
+     * @covers \Engelsystem\Controllers\SettingsController::savePassword
+     */
+    public function testSavePasswordWhenEmpty()
+    {
+        $this->user->password = '';
+        $this->user->save();
+
+        $body = [
+            'new_password'  => 'anotherpassword',
+            'new_password2' => 'anotherpassword'
+        ];
+        $this->request = $this->request->withParsedBody($body);
+
+        $this->setExpects($this->auth, 'user', null, $this->user, $this->once());
+        $this->setExpects($this->auth, 'setPassword', [$this->user, 'anotherpassword'], null, $this->once());
+        $this->setExpects(
+            $this->response,
+            'redirectTo',
+            ['http://localhost/settings/password'],
+            $this->response,
+            $this->once()
+        );
+
+        /** @var SettingsController $controller */
+        $controller = $this->app->make(SettingsController::class);
+        $controller->setValidator(new Validator());
+        $controller->savePassword($this->request);
+    }
+
     /**
      * @covers \Engelsystem\Controllers\SettingsController::savePassword
      */
-- 
2.34.0
```

**Comment by MyIgel** [comment]
And a fix for the "broken" registration page, can be applied using `git am 0002-Only-allow-sso-registration-if-password-field-is-disabled.patch`:
```patch
From b911b3e977ab590d2cd77d7bc0ab36e6cdc75694 Mon Sep 17 00:00:00 2001
From: Igor Scheller <igor.scheller@igorshp.de>
Date: Fri, 10 Dec 2021 01:51:04 +0100
Subject: [PATCH] Only allow sso registration if password field is disabled

---
 config/config.default.php        | 4 ++--
 includes/pages/guest_login.php   | 8 +++++++-
 resources/lang/de_DE/default.po  | 3 +++
 resources/views/pages/login.twig | 8 ++++++--
 4 files changed, 18 insertions(+), 5 deletions(-)

diff --git a/config/config.default.php b/config/config.default.php
index 47a7374a..9edb1f5e 100644
--- a/config/config.default.php
+++ b/config/config.default.php
@@ -229,8 +229,8 @@ return [
     'min_password_length'     => env('PASSWORD_MINIMUM_LENGTH', 8),
 
     // Whether the Password field should be enabled on registration.
-    // If this is disabled, it means that no password can be set on registration so the user will
-    // not be able to log in unless linked to an oauth provider.
+    // This is useful when using oauth, disabling it also disables normal
+    // registration without oauth.
     'enable_password'         => (bool)env('ENABLE_PASSWORD', true),
 
     // Whether the DECT field should be enabled
diff --git a/includes/pages/guest_login.php b/includes/pages/guest_login.php
index 8d08b6a5..124c66a7 100644
--- a/includes/pages/guest_login.php
+++ b/includes/pages/guest_login.php
@@ -36,6 +36,7 @@ function guest_register()
     $config = config();
     $request = request();
     $session = session();
+    $is_oauth = $session->has('oauth2_connect_provider');
 
     $msg = '';
     $nick = '';
@@ -63,7 +64,12 @@ function guest_register()
         }
     }
 
-    if (!auth()->can('register') || (!$authUser && !config('registration_enabled'))) {
+    if (
+        !auth()->can('register') // No registration permission
+        // Not authenticated and
+        || (!$authUser && !config('registration_enabled')) // Registration disabled
+        || (!$authUser && !$enable_password && !$is_oauth) // Password disabled and not oauth
+    ) {
         error(__('Registration is disabled.'));
 
         return page_with_title(register_title(), [
diff --git a/resources/lang/de_DE/default.po b/resources/lang/de_DE/default.po
index eb2574c3..3a386af0 100644
--- a/resources/lang/de_DE/default.po
+++ b/resources/lang/de_DE/default.po
@@ -188,6 +188,9 @@ msgstr "Passwort vergessen"
 msgid "Please sign up, if you want to help us!"
 msgstr "Bitte registriere Dich, wenn Du helfen möchtest!"
 
+msgid "Registration is only available via external Login."
+msgstr "Die Registrierung ist nur über einen externen Login möglich."
+
 #: resources/views/pages/login.twig:90 includes/pages/guest_login.php:61
 msgid "Registration is disabled."
 msgstr "Registrierung ist abgeschaltet."
diff --git a/resources/views/pages/login.twig b/resources/views/pages/login.twig
index 95220b1d..b971bde0 100644
--- a/resources/views/pages/login.twig
+++ b/resources/views/pages/login.twig
@@ -100,8 +100,12 @@
             <div class="col-sm-6 text-center">
                 <h2>{{ __('Register') }}</h2>
                 {% if has_permission_to('register') and config('registration_enabled') %}
-                    <p>{{ __('Please sign up, if you want to help us!') }}</p>
-                    <a href="{{ url('register') }}" class="btn btn-primary">{{ __('Register') }} &raquo;</a>
+                    {% if config('enable_password') %}
+                        <p>{{ __('Please sign up, if you want to help us!') }}</p>
+                        <a href="{{ url('register') }}" class="btn btn-primary">{{ __('Register') }} &raquo;</a>
+                    {% else %}
+                        <p>{{ __('Registration is only available via external Login.') }}</p>
+                    {% endif %}
                 {% else %}
                     {{ m.alert(__('Registration is disabled.'), 'danger') }}
                 {% endif %}
-- 
2.34.0
```

**Comment by MyIgel** [comment]
And an extension to make the password field configurable via oauth settings:
`git am 0003-Make-password-enabled-configurable-via-oauth-setting.patch`

```diff
From 683793939e3833451e06073d3719a41769143a67 Mon Sep 17 00:00:00 2001
From: Igor Scheller <igor.scheller@igorshp.de>
Date: Fri, 10 Dec 2021 01:22:02 +0100
Subject: [PATCH] Make password enabled configurable via oauth settings

---
 config/config.default.php                      | 2 ++
 includes/pages/guest_login.php                 | 5 +++++
 src/Controllers/OAuthController.php            | 9 ++++++++-
 tests/Unit/Controllers/OAuthControllerTest.php | 1 +
 4 files changed, 16 insertions(+), 1 deletion(-)

diff --git a/config/config.default.php b/config/config.default.php
index 7e539b39..3806fd57 100644
--- a/config/config.default.php
+++ b/config/config.default.php
@@ -105,6 +105,8 @@ return [
             'hidden' => false,
             // Mark user as arrived when using this provider (optional)
             'mark_arrived' => false,
+            // If the password field should be enabled on registration (optional)
+            'enable_password' => false,
         ],
         */
     ],
diff --git a/includes/pages/guest_login.php b/includes/pages/guest_login.php
index 62e08971..33a9842e 100644
--- a/includes/pages/guest_login.php
+++ b/includes/pages/guest_login.php
@@ -65,6 +65,11 @@ function guest_register()
         }
     }
 
+    $oauth_enable_password = $session->get('oauth2_enable_password');
+    if (!is_null($oauth_enable_password)) {
+        $enable_password = $oauth_enable_password;
+    }
+
     if (
         !auth()->can('register') // No registration permission
         // Not authenticated and
diff --git a/src/Controllers/OAuthController.php b/src/Controllers/OAuthController.php
index fd83688a..0dcdaa5b 100644
--- a/src/Controllers/OAuthController.php
+++ b/src/Controllers/OAuthController.php
@@ -329,7 +329,13 @@ class OAuthController extends BaseController
         }
 
         $config = array_merge(
-            ['username' => null, 'email' => null, 'first_name' => null, 'last_name' => null],
+            [
+                'username' => null,
+                'email' => null,
+                'first_name' => null,
+                'last_name' => null,
+                'enable_password' => false,
+            ],
             $config
         );
         $this->session->set(
@@ -349,6 +355,7 @@ class OAuthController extends BaseController
         $this->session->set('oauth2_access_token', $accessToken->getToken());
         $this->session->set('oauth2_refresh_token', $accessToken->getRefreshToken());
         $this->session->set('oauth2_expires_at', $expirationTime);
+        $this->session->set('oauth2_enable_password', $config['enable_password']);
 
         return $this->redirector->to('/register');
     }
diff --git a/tests/Unit/Controllers/OAuthControllerTest.php b/tests/Unit/Controllers/OAuthControllerTest.php
index 66181f55..4a8460f5 100644
--- a/tests/Unit/Controllers/OAuthControllerTest.php
+++ b/tests/Unit/Controllers/OAuthControllerTest.php
@@ -389,6 +389,7 @@ class OAuthControllerTest extends TestCase
         $this->assertEquals('test-token', $this->session->get('oauth2_access_token'));
         $this->assertEquals('test-refresh-token', $this->session->get('oauth2_refresh_token'));
         $this->assertEquals(4242424242, $this->session->get('oauth2_expires_at')->unix());
+        $this->assertFalse($this->session->get('oauth2_enable_password'));
         $this->assertEquals(
             [
                 'name' => 'username',
-- 
2.34.0
```

**Comment by fabianfreyer** [comment]
This should work, it's enabled.
image

**Comment by MyIgel** [comment]
Then it's buggy, eventually configure it to no and then back to yes?

```
$ git push fabianfreyer password-required
ERROR: Permission to fabianfreyer/engelsystem.git denied to MyIgel.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
``
Esp. as I can also see the "You can push changes" message but get the above error.

![Screenshot_20211210_205657](https://user-images.githubusercontent.com/1448057/145633934-5f7d2179-5967-44b4-a7d9-12d4e9cf6921.png)
`

**Comment by fabianfreyer** [comment]
I dis- and re-enabled the checkbox, does it work now?

**Comment by MyIgel** [comment]
Nope. sadly the same problem, hmm
Maybe @msquare could have a look if GitHub changed some permissions around or something?

Its starange, anyway..

I'v pushed my changes to a rebased branch: https://github.com/MyIgel/engelsystem/tree/password-required

**Comment by msquare** [comment]
@fabianfreyer since you work on a fork of a fork of the engelsystem, the push does not work for us. Pushing to forks of forks is not supported by Github. You may fork our engelsystem project directly and reapply your pr. Would that be possible for you?

**Comment by MyIgel** [comment]
(Or push the content of my branch to yours ^^)

**Comment by MyIgel** [comment]
I rebased the above branch onto the current `main`, @fabianfreyer feel free to use that one and force push it to your branch or create a new pull request based on it

**Comment by fabianfreyer** [comment]
Thanks for checking, @msquare! Yes, that seems to be it.
@MyIgel I've reset this branch to your `password-required` branch.

**Comment by MyIgel** [comment]
@fabianfreyer hmm it currently has conficts -> do you want to have a look? :D

**Comment by MyIgel** [comment]
I reased it onto the current main in https://github.com/MyIgel/engelsystem/tree/password-required

**Comment by msquare** [comment]
This will be merged via #887 
Unfortunately this doesn't count as hacktoberfest pr. (I guess...)

**Comment by MyIgel** [comment]
Thank you for reviewing! (and it would definitely be too late for Hacktoberfest ;))

**Pull request closed without merging**
