### PR TITLE
Recreated shift type admin backend

### PR DESCRIPTION
**Pull request by MyIgel**

### CODE REVIEW

**Comment by xuwhite** [comment]
I cont reach the side of a specific shift type

**Comment by MyIgel** [comment]
> I cont reach the side of a specific shift type

It got removed as it provides no relevant additional information but i could add it if needed

**Comment by xuwhite** [comment]
Pls implement a back button for the editing shift type page

**Comment by xuwhite** [comment]
There is no shift type delete page. That results in for my taste to easy deletion of possibly many shifts.
Screenshot 2023-11-03 at 17 08 33
image of the old shift type delete page

**Comment by xuwhite** [comment]
I dont think its usefull to have two ways of being able to delete a shift type (at the overview and at the edit page)

**Comment by xuwhite** [comment]
other than that I like it ☺️

**Comment by MyIgel** [comment]
The back button and details page is reimplemented, needed the rebase

**Comment by MyIgel** [comment]
The deletion part requires #1247

**Comment by MyIgel** [comment]
Deletion is now implemented too

**Review by msquare — APPROVED** [review]

**Pull request merged**
