### PR TITLE
Mobile required Option

### PR DESCRIPTION
**Pull request by PowerPan**
Add Option to make mobile number required for Registration

### CODE REVIEW

**Comment by PowerPan** [comment]
@MyIgel @weeman1337 what i have to do for merging?

**Review by MyIgel — CHANGES_REQUESTED** [review]
At the moment this PR has merge conflicts so a rebase would be required here.
Also to implement this option properly the same checks should be added to the users settings page (which will interfere with #972 (Settings profile modernization) so I would recommend eventually waiting for that one to be merged first)

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Hey @PowerPan :wave: Can you fix the issues mentioned by previous reviewers and solve the conflicts in your branch? If we don't hear from you for another two weeks, we may unfortunately close this pull request.

**Comment by weeman1337** [comment]
If you want to continue working on this after two weeks, just leave comment here so that we can reopen the pull request.

**Comment by MyIgel** [comment]
Hi @PowerPan, for what event do you need that change and are you able to update this PR to also cover the user page input? If yes, feel free to reopen this PR :)

**Pull request closed without merging**
