### PR TITLE
Fixed the type error and syntax error

### PR DESCRIPTION
**Pull request by kamishettysreeja25**
@msquare Please review it 
screenshot from 2016-03-23 20 20 54
screenshot from 2016-03-23 20 21 28
instead of mysqli_provider.php  mysql_provider.php was linked fixed it 
Thank You :)

### CODE REVIEW

**Comment by msquare** [comment]
Hi,
thank you for investing time to improve the engelsystem. The update.php is legacy code and not needed anymore. You can simply delete it (and the directory update.d too).

**Comment by kamishettysreeja25** [comment]
@msquare  
Thank You, So can we delete all the unused files and update the repository so that it is easy to  contribute.
Can you tell all the unused files,  i will update it  :) .

**Comment by msquare** [comment]
update.php and the update.d directory can be deleted. There may be more files, but I don't now them.

**Comment by kamishettysreeja25** [comment]
@msquare 
I have deleted the unused files , if anything else is needed to be done please suggest me .
thanks :)

**Comment by mariobehling** [comment]
@msquare Hi, we would like to work on the Engelsystem and add some features we need at FOSSASIA. Should we fork the project to the FOSSASIA repo? I see that this change has not been merged yet and wonder what is your suggestion to engage our students.

**Pull request closed without merging**
