### PR TITLE
Config switches

### PR DESCRIPTION
**Pull request by PowerPan**
Fix Some Config Switches Frontend Configurations

### CODE REVIEW

**Comment by PowerPan** [comment]
@MyIgel @weeman1337 what i have to do for merging?

**Comment by xuwhite** [comment]
Please have a look at the [contributing guidelines](https://github.com/engelsystem/engelsystem/blob/main/CONTRIBUTING.md), especially the parts about meaningful commit messages, squashing and code style.

**Review by MyIgel — CHANGES_REQUESTED** [review]
As Xu pointed out, this PR  needs some changes

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Hey @PowerPan :wave: Can you fix the issues mentioned by previous reviewers and solve the conflicts in your branch? If we don't hear from you for another two weeks, we may unfortunately close this pull request.

**Comment by weeman1337** [comment]
If you want to continue working on this after two weeks, just leave comment here so that we can reopen the pull request.

**Comment by MyIgel** [comment]
This PR took me definitively too much time to rebase, review and fix. Testing the changes in all config combinations on the relevant pages is desired for next PRs.

**Pull request merged**
