### PR TITLE
Permissions refactoring

### PR DESCRIPTION
**Pull request by MyIgel**
Replaced Privileges/Groups with corresponding models (the rename and restructuring according to #740 (RFC/Draft: New permissions concept) has to be done at a later stage ;)

### CODE REVIEW

**Comment by MyIgel** [comment]
@weeman1337 / @msquare could you have a look / review / test this one and point me to things that i missed? :D

**Comment by MyIgel** [comment]
Another open question would be how to proceed with the "sorting" of groups, eventually the user edit page should be changed to only allow assigning groups to others that an angel has itself?

**Comment by MyIgel** [comment]
(And those commits should definitely be squashed on merge as they leave a broken engelsystem on their own)

**Review by weeman1337 — APPROVED** [review]
Looks good

**Pull request merged**
