### PR TITLE
Shift view flex

### PR DESCRIPTION
**Pull request by PowerPan**
Make Shift View Height More Flexibel

In the Screenshot you can see how it looks like with 1800
Bildschirmfoto 2022-07-15 um 21 55 34

And Here with the default of 900
Bildschirmfoto 2022-07-15 um 21 56 14

### CODE REVIEW

**Comment by PowerPan** [comment]
@MyIgel @weeman1337 what i have to do for merging?

**Review by MyIgel — CHANGES_REQUESTED** [review]
Hi, could you please have a look at the [contributing guidelines](https://github.com/engelsystem/engelsystem/blob/main/CONTRIBUTING.md) and rebase that PR on the current main branch? 
The random merge seems a bit out of place here and this PR contains changes to the admin_user file which is already covered by another PR.

Also it needs a rebase (or cherry picking) as some files changed in the meantime.

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Hey @PowerPan :wave: Can you fix the issues mentioned by previous reviewers and solve the conflicts in your branch? If we don't hear from you for another two weeks, we may unfortunately close this pull request.

**Comment by weeman1337** [comment]
If you want to continue working on this after two weeks, just leave comment here so that we can reopen the pull request.

**Comment by weeman1337** [comment]
Unfortunately we didn't hear back from you. I am going to close this now. If you want continue to work on this re-open the PR.

**Pull request closed without merging**
