### PR TITLE
Fix initial setup bugs

### PR DESCRIPTION
**Pull request by noc0lour**
I found several issues during initial setup with a MySQL server version 5.7.19.  Apparently some default settings changed in mysql server 5.7 and up the server is more strict by default.

### CODE REVIEW

**Comment by MyIgel** [comment]
@msquare I think we should merge this to feature-igel-rewrite

**Comment by msquare** [comment]
Yes.

**Comment by MyIgel** [comment]
Its already merged with my local branch containing more improvements -> PR in progress (First I have to write more tests...)

**Comment by msquare** [comment]
Thank you. We included your changes in the rewrite.

**Pull request closed without merging**
