### PR TITLE
PHP 8.2 compatibility, bump min. version to 8.1

### LINKED ISSUE #1022: Drop PHP 7.4 Support
PHP 7.4 isn't supported any more: https://www.php.net/supported-versions
Instead we should check if PHP 8.2 (today released) works

### PR DESCRIPTION
**Pull request by MyIgel**
Make the Engelsystem PHP 8.2 compatible and updates packages

Closes #1022

### CODE REVIEW

**Comment by MyIgel** [comment]
At the moment it requires https://github.com/FakerPHP/Faker/pull/570 to be merged and a new package version released for the CI to run without warnings which get converted to errors.

**Comment by ximex** [comment]
why not allow 8.0? It's still supported
also update node?
`FROM node:14-alpine as themes` -> `FROM node:18-alpine as themes`

**Comment by MyIgel** [comment]
Updating node is way out of scope here..
We could move the 8.1 update to a later date but it would be useful to already have support for some 8.1 features like new in initializers and intersection types but that can be discussed i guess. There might also be some package dependencies which i had to check then again.

**Comment by MyIgel** [comment]
(and also the current stable / lts versions of debian and ubuntu package 8.1 so thats no problem either)

**Comment by MyIgel** [comment]
Faker got updated so this can be tested and merged :tada:

**Review by weeman1337 — APPROVED** [review]

**Pull request merged**
