### PR TITLE
Shifts feed: Added URL to shit and shifttype name & description

### LINKED ISSUE #1104: API for shift types
As far as I understand shift types can be created and changed at any time in an Engelsystem instance.

The shifts JSON currently exposes the IDs of shift types `shifttype_id` as integers.

Is there an API for the human readable shift type names or plans to integrate them in the shifts JSON response?

### PR DESCRIPTION
**Pull request by MyIgel**
Closes #1104

New output:

```json
[
  {
    "id": 3,
    "shift_id": 198,
    "angel_type_id": 1,
    "user_id": 1,
    "user_comment": "",
    "freeloaded": false,
    "title": "Bar Runner",
    "description": "Foo Bar!\n**Baz!**",
    "url": "",
    "start": 1685829600,
    "end": 1685836800,
    "shift_type_id": 4,
    "room_id": 1,
    "transaction_id": "d171dc41-7ab7-4470-91bb-8668ba725242",
    "created_by": 1,
    "updated_by": 1,
    "created_at": "2023-06-04 22:29:53",
    "updated_at": "2023-10-17 19:29:19",
    "shift": {
      // ...
      },
      "shift_type": {
        "id": 4,
        "name": "Schichttyp1",
        "description": "The first shift type or whatever"
      }
    },
    "name": "Schichttyp1",
    "link": "http://localhost:5080/shifts?action=view&shift_id=198",
    "Comment": "",
    "SID": 198,
    "shifttype_id": 4,
    "shifttype_name": "Schichttyp1",
    "shifttype_description": "The first shift type",
    "URL": "",
    "RID": 1,
    "Name": "Testraum",
    "map_url": null,
    "start_date": "2023-06-04T00:00:00+02:00",
    "end_date": "2023-06-04T02:00:00+02:00",
    "timezone": "+02:00",
    "event_timezone": "Europe/Berlin"
  },
// ...
]
```

### CODE REVIEW

**Comment by xuwhite** [comment]
Ugly but works

**Comment by johnjohndoe** [comment]
Thank you. I hope to find time soon to integrate it.

**Comment by johnjohndoe** [comment]
@MyIgel Are the `shifttype_name` and `shifttype_description` **required** (cannot be missing in the JSON) or **optional** (empty string or text value) attributes?

**Comment by MyIgel** [comment]
@johnjohndoe as its in the `$data` array in https://github.com/engelsystem/engelsystem/blob/main/src/Controllers/FeedController.php#L71 its a somewhat hard requirement in the meaning that it will be there (on coming engelsystem releases starting with the current main). The name should contain a value as it would be pretty useless to not have one, the description is optional so could be an empty string. The data types should not change but eventually its better to force cast them (and generally  take everything with a grain of salt here, for examples unwanted nulls in other fields).

On the long run there will be a properly defined API of which its first steps are currently being implemented in #1158 but that might take some time to evolve (but contains better documentation).

**Comment by johnjohndoe** [comment]
@MyIgel What is the difference between `name` and `shifttype_name`?

**Comment by MyIgel** [comment]
@johnjohndoe there is none but 'name' is somewhat not describing it enough (and not to be confused with `Name` which is the room name) so shifttype_name is the "better" wording?

**Comment by johnjohndoe** [comment]
Thank you. I agreed. Then we can declare `name` as deprecated in favor of `shifttype_name`.

**Comment by MyIgel** [comment]
I updated the docs for that in #1248

**Comment by johnjohndoe** [comment]
:arrow_up: Now available in the [engelsystem library v.8.0.0](https://github.com/johnjohndoe/engelsystem/releases/tag/v.8.0.0). Thank you!

**Comment by johnjohndoe** [comment]
:arrow_up: Now available in the [EventFahrplan app](https://github.com/EventFahrplan/EventFahrplan/pull/574). Thank you!

**Pull request merged**
