### PR TITLE
styling 35c3: Lighten the font color

### PR DESCRIPTION
**Pull request by MyIgel**

### CODE REVIEW

**Comment by zichy** [comment]
Do you have a screenshot of how `lighten(@gray, 15%)` would look like? The contrast ratio should be at least 4.5:1 to meet the [WCAG](https://www.w3.org/TR/WCAG21/) criteria. `#757574` would be fine, `#BBBBB9` is even better.

**Comment by MyIgel** [comment]
The `lighten(@gray, 15%)` sets the color to `#737372` so it should be enough ;)
Imho a `#BBBBB9` would look (at that point) like white and that would not represent the color scheme of the congress.

**Comment by msquare** [comment]
Ok, lets go. Usability before design specifications again.

**Comment by MyIgel** [comment]
At least the c3groc does not see any strict design requirements ;)

> Feel free to choose a light gray :)
> Bad contrast is "form fucks function" but so aesthetic ;)
>
> Source: https://twitter.com/c3groc/status/1069689215313694721

**Pull request merged**
