### PR TITLE
Fix mobile navi

### PR DESCRIPTION
**Pull request by digitaldonkey**

### CODE REVIEW

**Comment by digitaldonkey** [comment]
Should fix https://github.com/engelsystem/engelsystem/issues/249

**Comment by digitaldonkey** [comment]
Bildschirmfoto vom 2019-12-30 14-09-47
Bildschirmfoto vom 2019-12-30 14-10-38

**Comment by MyIgel** [comment]
Hmm, i see a not klickable info sign ;)
image

Which should show an info message for example when there are open questions
image

and the `X` looks somehow distorted?

**Comment by digitaldonkey** [comment]
Can you give me a hint how to reproduce that in developing stack?

Igor Scheller <notifications@github.com> schrieb am Mo., 30. Dez. 2019,
17:04:

**Comment by MyIgel** [comment]
Just use the "Ask the heaven" functionality ;)

**Comment by digitaldonkey** [comment]
Updated Messages display. 
Please retry. I might not have seen other issues.

**Comment by digitaldonkey** [comment]
The X is still distorted... ;)

**Pull request merged**
