### PR TITLE
update libs and move bootstrap-icons to dependencies

### PR DESCRIPTION
**Pull request by ximex**
there is no button to allow edits:
grafik

### CODE REVIEW

**Comment by MyIgel** [comment]
Thats interesting, hmm.
Normally that can happen if you use a fork of a fork but that does not seem to be the case. Do you have some interesting security settings active? Or is you account somehow managed by an org?

**Comment by ximex** [comment]
i think i found the problem. not possible from an organization: https://github.com/orgs/community/discussions/5634

**Comment by ximex** [comment]
@MyIgel fixed

**Review by weeman1337 — APPROVED** [review]
Did a quick test. Looks good :+1:

**Pull request merged**
