### PR TITLE
added ability to send messages to angeltypes

### PR DESCRIPTION
**Pull request by allentje**
#### What does this PR do?
This allows messages to be sent to angeltypes so that you no longer need to send the same message for every user.
This PR is meant to solve issue #562

#### Where should the reviewer start?
Message page

#### How should this be manually tested?
- [ ] make sure to have some users connected to a angel type
- [ ] send message by selecting the angeltype from the drop down
- [ ] check that the angels connected to the angel type now have a new message

#### What should happen on deployment? (check all that apply)
- [ ] The usual steps.

### CODE REVIEW

**Comment by allentje** [comment]
Thank you for your feedback.
It wasn't entirely clear to me what the exact specifications of the issue was but reading what you have wrote I think I know understand adjustments should be made.

To prevent any misunderstandings would this link, when clicked, jump to the message page I had already edited but with the Angeltype already defined? E.g replace drop-down with the Angeltype as a text.

**Comment by MyIgel** [comment]
> To prevent any misunderstandings would this link, when clicked, jump to the message page I had already edited but with the Angeltype already defined? E.g replace drop-down with the Angeltype as a text.

I think I would completely remove the dropdown from the messages page and add a parameter to the url to send to angeltypes (and of course checking if the user is allowed to send to a group), on the message page then the user select would be replaced by the static angeltype name.

**Comment by allentje** [comment]
Yes ok, that's exactly what I mean. Then we are on the same page :) I will update the pr in the coming days.

**Comment by MyIgel** [comment]
> I will update the pr in the coming days.

Did you already had time to update it?

**Comment by allentje** [comment]
>>I will update the pr in the coming days.

>Did you already had time to update it?

I did but I wasn't completely finished with it yet. My apologies for the delay, I have been doing a lot of late evenings at work. I have some free days coming up so I will update it then.

**Comment by MyIgel** [comment]
Hi, it would be nice if you could commit the changes that you did here so maybe i can update the remaining part?

**Comment by allentje** [comment]
I'll do it this evening after I have finished work

**Comment by allentje** [comment]
I will see what I can fish out from the old project this evening but I think it will be tomorrow when I push if that's fine for you?. Only just got home from work.

**Comment by MyIgel** [comment]
No problem, its nice to see that there is progress :)

(and that i can merge it before changing the part of the Engelsystem ^^)

**Comment by allentje** [comment]
Don't worry, I haven't forgotten.
I need more time to extract the code and look into the changes due to trying to extract the changed code from a backup. 
I will try to have this done by the weekend.

**Comment by allentje** [comment]
It isn't quite finished yet. I still need to hook the message url to the angel type page.
The dropdown has now been replace by the angel type when that is given through the url.
I also still need to add the validation

**Comment by msquare** [comment]
Ping @allentje?

**Comment by BlackAfri** [comment]
I would be very interested in sending a message or email to all members of an angel type.
Is this issue still in progress? @allentje @MyIgel

**Comment by Corborax** [comment]
I'd also love to be able to send a message or email all members of an angel type (or a specific room).
Is this issue still in progress? :) @allentje @MyIgel   Maybe related to #757

**Comment by allentje** [comment]
> Is this issue still in progress? :) @allentje @MyIgel   Maybe related to #757 
I am not working on this issue anymore. Perhaps you can see my last comment and adapt the changes I have already made.

**Comment by msquare** [comment]
@allentje thanks for the feedback, I will close this pr now.

**Pull request closed without merging**
